### ISSUE TITLE
No Module Named Requests

### ISSUE THREAD

**Issue by andrijan** [james9909/stackanswers.vim#1]
When trying this I get this error:

```
"__Answers__" [New File]
Error detected while processing function <SNR>87_StackAnswers..provider#python#Call:
line    1:
ImportError('No module named requests',)
NameError("name 'stackAnswers' is not defined",)
```

**Comment by james9909** [comment]
Sorry, I should make it clear that this plugin uses the requests, lxml, and beautifulsoup modules.

**Comment by pdbradley** [comment]
I had a similar error on OSX.  Didn't even have pip with the system python, so did brew install python, then pip install requests, lxml, and beautiful soup.

Now I'm here:

```
Error detected while processing function <SNR>36_StackAnswers:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/philip/.vim/bundle/stackanswers.vim/plugin/stackanswers.py", line 1, in <module>
    import requests
  File "/usr/local/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/site-packages/requests/utils.py", line 12, in <module>
    import cgi
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cgi.py", line 50, in <module>
    import mimetools
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyErr_ReplaceException
  Referenced from: /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'stackAnswers' is not defined
```

**Comment by james9909** [comment]
Can you import requests outside of vim?

**Comment by andrijan** [comment]
```
$ pip install requests
Requirement already satisfied (use --upgrade to upgrade): requests in /Library/Python/2.7/site-packages
Cleaning up...

$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named requests
>>>
```

**Comment by james9909** [comment]
I'm no expert on OS X, but I think the problem is which python is being run, since you may have multiple python executables. Try using easy_install instead of pip.

**Comment by andrijan** [comment]
Same error, but okay, might be my local setup.

**Comment by ybur-yug** [comment]
@andrijan I am having the same issue. My install process was as follows:

```
$ brew install python
$ pip install lxml
$ pip install requests
$ pip install beautifulsoup4
$ # open ~/.vimrc and add `Plugin james9909/stackanswers.vim` to my vundle section
$ # run :PluginInstall
$ vim
$ # now if I run :StackAnswers I get the same output as you
```

I imagine its in how OS X calls python, as with RVM and ruby I can't run `:! ruby -e 'puts "bar"'` because it cannot detect that ruby is installed via RVM. Sounds similar...

**Comment by james9909** [comment]
If anyone is running OS X and would like to offer a solution, that would be great.

**Comment by ybur-yug** [comment]
I will be toying with it @james9909 , will PR with a mention in the README if I figure something out.

**Comment by pdbradley** [comment]
I was able to run python and import requests outside of vim.  But still get the same problem.  I'm very new to python.

**Comment by ghost** [comment]
OSX already has python built in and it is known to have issues with brew python. You can try doing this:
`brew install python --override-system-python` but that's a bit dangerous. It's better to just uninstall brew python and stick with system python.
